### ISSUE TITLE
tables layout and database script

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#10]
sql script for creating the database should be written
- [x] tables and fields discussed
- [x] sql script for creating the tables should be created 
- [x] all the needed fields for hibernate is added
- [x] initial data
- [ ] review the script

**Comment by mbaniasad** [comment]
@bonkilejay @ricarda42 @mzeen 
this is a very important issue. any changes in this issue would have impacts on everyone else .
I have mentioned you here so you all get notified if there is a change.
if there is change here please merge it to your working copy
ps: sorry for getting to many mails

**Comment by rrosemann** [comment]
@mbaniasad In the creator the bus gets an attribute lineId, but I can't find it in the Master_Data file, so this might be why I get an error when trying to call the bus objects.

**Comment by rrosemann** [comment]
I get  the following error:
2016-05-17 14:38:01.811  WARN 5663 --- [nio-8081-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 42122, SQLState: 42S22
2016-05-17 14:38:01.812 ERROR 5663 --- [nio-8081-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Column "BUSENTITY0_.TIMESTAMP" not found; SQL statement:
select busentity0_.id as id1_0_, busentity0_.modificationCounter as modifica2_0_, busentity0_.color as color3_0_, busentity0_.lineId as lineId4_0_, busentity0_.numberPlate as numberPl5_0_, busentity0_.picture as picture6_0_, busentity0_.timeStamp as timeStam7_0_ from BUS busentity0_ [42122-190]
Error: could not prepare statement; SQL [select busentity0_.id as id1_0_, busentity0_.modificationCounter as modifica2_0_, busentity0_.color as color3_0_, busentity0_.lineId as lineId4_0_, busentity0_.numberPlate as numberPl5_0_, busentity0_.picture as picture6_0_, busentity0_.timeStamp as timeStam7_0_ from BUS busentity0_]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement

The code of the bus component should be in complete analogy to the line component, so I don't see why it does not work. (Line component works fine) There might be some problem with the data base, but as I am not familiar with data bases and SQL, I don't know how to fix this.
@mbaniasad @razadfki @maybeec I would be grateful if someone could help.

**Comment by razadfki** [comment]
@ricarda42 go to following files
`buergerbusserver\core\src\main\resources\db\migration\V0002__R001_Master_data.sql
buergerbusserver\core\src\main\resources\db\migration\h2\V0001__R001_Create_schema.sql`
there you'll find statements for bus in **Create** and **Insert** replace the first timestamp in create with Capital ones e.g., **"timestamp"** -> **"TIMESTAMP"**
and replace again in Insert statement.

**Comment by rrosemann** [comment]
Thanks a lot, it works now :-)
