### ISSUE TITLE
Communication Channel

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#11]
You should discuss (and tell us) which communication channel you use. 

As Ricarda could not use WhatsApp, you may switch to e-mails.

**Comment by mbaniasad** [comment]
mailing group will be used for discussions and any important issues or decisions would be announced there as well.
- [x] tell the guys in whatsapp channel that noting should be missed 
- [x] send mail about moving from trello to Githhub issue tracker
