### ISSUE TITLE
Create System functions in requirements

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#12]
- [x] You should document, which system functions your server supports,
  e.g. #SF_S1 Provide Interface to apps, #SF_S2 Store information
  Of course you would need to describe each system function in detail and my proposal might not be complete or the best one.
- [ ] The system functions must be traced to the To-Be scenarios.
  See for more details in GSE-Project/SS2016-group2#17

**Comment by captain-red-baron** [comment]
first point has been done be me, waiting for review

**Comment by ChristianAGSE** [comment]
Hello Marcel (@mmueller301),

thank you that you did the task, but I assigned it to group No.1, so it was a misassignment by me. I am sorry. 

@mbaniasad: May you coordinate the review and the second point.

**Comment by rrosemann** [comment]
I have reviewed the first part (possibly again, there is someone mentioned as a reviewer) and traced the system functions to to-be-scenarios, this still needs to be reviewed.

**Comment by rrosemann** [comment]
I just changed the system functions, because so far they didn't convey much information and it would have been hard to properly verify compliance of our product with requirements based on these. The old version is now in our drive. This still needs reviewing!
