### ISSUE TITLE
Change of Req Doc (until May 24)

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#14]
- [x] Change of the requirements document (until Tuesday May 24).
  Each Group should get a list of system functions that are new and which might require a change.
- [x] Communication of API extension (until Tuesday May 24)

**Comment by ChristianAGSE** [comment]
There are no additional features for iteration 2.

The only part that is missing is a section of features, that you would like to implement in upcoming sections. The features can be described with one Identification number and a one-line description.

i.e.:
FUT_1 Localize strings (allow German and English language in the app)
FUT_2 support custom stops
FUT_3 ... 

FUT stands for future

**Comment by rrosemann** [comment]
I added some future system functions based on the system functions described by group 2 and 3 which were marked as for future iterations. Needs review! (As much as the other server system functions, see #12 ). If the other teams add more system functions I can derive those for the server as well.

**Comment by rrosemann** [comment]
System functions should be done completely now, please review.

**Comment by mbaniasad** [comment]
done review.
the system functions for the next iterations marked as TODO to be discussed
