### ISSUE TITLE
System testing iteration 1&2

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#15]
- [ ] Creation of system test cases until Fr May 27
- [ ] Test execution and documentation in week of June 06 to June 10.

**Comment by mbaniasad** [comment]
@mzeen system test cases should be implemented by the end of this Iteration
- [x] create a sample test case and learn how to do testing and writing code for testing
- [x] add test for all the interfaces which are in the interface document

**Comment by mzeen** [comment]
Started working on sample test case

**Comment by mzeen** [comment]
@mbaniasad Uploades a sample test case under a folder named as Test, need review on that.

**Comment by mzeen** [comment]
Issue #15, I need complete requirement document, the test cases I wrote according to server interface is quite not  satisfied by christian. and from now all communication through some traceable platform, not personal messages.

**Comment by rrosemann** [comment]
I'm reviewing your test cases just now and will redo the tests

**Comment by rrosemann** [comment]
Could you add a word document for the test cases as well? I can't edit the pdf file, at least I don't know how.

**Comment by mzeen** [comment]
@ricarda42 check the docx file.

**Comment by rrosemann** [comment]
Thanks.

**Comment by ChristianAGSE** [comment]
@ricarda42: Is there anything left to do?

**Comment by ChristianAGSE** [comment]
I changed the title of the issue, as it tracks the system testing of iteration 1&2

**Comment by rrosemann** [comment]
I just realized that this issue also consists of the test execution and not just creation of test cases, which I hadn't kept in mind when closing the issue. @mbaniasad, will you please document test results in the test cases file (of integration tests)?
Sorry for not realizing any earlier. Main work of this issue is done however.

**Comment by mbaniasad** [comment]
will be done today 15/06

**Comment by razadfki** [comment]
@mbaniasad reflection of #70 is required in here. Don't forget!
