### ISSUE TITLE
"stop" component implementation

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#16]
- [x]  code for stop 
  - [x] entity
  - [x] dao 
  - [x] management
  - [x] eto
  - [x] restservice
- [ ]  stop services 
  - [ ] ./stops intreface should be implemented.(check interface document) (in 2 part) 
    - [x]  1- without schedules 
    - [x]  2- adding schedules (consult me if needed help)
- [ ] review by reviewer
- [ ] verification of interface output with client group

**Comment by bonkilejay** [comment]
Need help for the " schedules " of stop component.

**Comment by mbaniasad** [comment]
working on schedules now

**Comment by mbaniasad** [comment]
@bonkilejay please ask @may-bee  how we can integrate schedules into this as it is in the interfaces.
@may-bee (we need help in creating the join and also integrating a list of the other object in this object's json output )

**Comment by mbaniasad** [comment]
route object reference in Stop etodoes not make scene

**Comment by ChristianAGSE** [comment]
you might add a date (i.e. as a comment text) until when you planned to have this task finished.
