### ISSUE TITLE
"route" component implementation

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#17]
- [x]  code for route 
  - [x] entity
  - [x] dao 
  - [x] management
  - [x] eto
  - [x] restservice
- [x]  rout services 
  - [x] ./routes intreface should be implemented.(check interface document)
    - for now we are considering the route an string of data(text);
- [x] review by reviewer (contact mohammd)
- [x] verification of interface output with client group

**Comment by mzeen** [comment]
I am having error while running on server. so I need to discuss my codes then I can Push.

**Comment by mzeen** [comment]
I pushed my code on branch name rootmanagement, having some issue which is unknown by me. unable to solve the problem. need help.

**Comment by mzeen** [comment]
still need someone to look at my code.

**Comment by mzeen** [comment]
Repeated column in mapping for entity: gse1.buergerbusserver.routemanagement.dataaccess.api.RouteEntity column: id (should be mapped with insert="false" update="false")

anyone know hoe to resolve this

**Comment by mzeen** [comment]
#23 Repeated column in mapping for entity: gse1.buergerbusserver.routemanagement.dataaccess.api.RouteEntity column: id (should be mapped with insert="false" update="false")

anyone know hoe to resolve this

**Comment by mzeen** [comment]
#23 Duplication Error resolved, Working code pushed in Branch RootManagement, Now waiting for review. @mbaniasad need review.

**Comment by razadfki** [comment]
@mbaniasad I'm reviewing.
@mzeen follow.

**Comment by mzeen** [comment]
Following...

**Comment by mzeen** [comment]
If review is done then can someone tell me how to implement this routemanagement with interface.

**Comment by mzeen** [comment]
@mbaniasad my code has been reviewed by @razadfki and I have made the changes. I need to know how to implement these code.

**Comment by mbaniasad** [comment]
what you mean you need to know how to implement the code?
if you mean you want to be able to see some result
http://localhost:8081/oasp4j-sample-server/services/rest/routmanagement/v1/routes

should return a list of routs. on your system browser

**Comment by mzeen** [comment]
not getting any result on browser Error:  javax.ws.rs.NotFoundException: HTTP 404 Not Found

**Comment by mzeen** [comment]
Still unable to resolve  Error: javax.ws.rs.NotFoundException: HTTP 404 Not Found

**Comment by mbaniasad** [comment]
will come for help soon.

**Comment by mzeen** [comment]
Now Link is working and it is also showing the values from database.

**Comment by mzeen** [comment]
@mbaniasad I did some changes in database, I change datatype of GPSData from TEXT to Varchar and add some INSERT query.

**Comment by mzeen** [comment]
@mbaniasad Route Component Implemented.

**Comment by mzeen** [comment]
verification of interface output with client group, Waiting for the response from the other group.

**Comment by mbaniasad** [comment]
- [ ] check for exception handling. check it with the sample project of OASP.

**Comment by ChristianAGSE** [comment]
The verification of the interface should be done in the beginning, after the interface meeting. This is done by asking yourself, how you would implement the interface.

In the end there should only be a validation to check, that it really works.

**Comment by ChristianAGSE** [comment]
you might add a date (i.e. as a comment text) until when you planned to have this task finished.

**Comment by mbaniasad** [comment]
@mzeen I have finished the coding for this. 
pleas review my code and verify the last checkbox with interface document

**Comment by mzeen** [comment]
code Reviewed and last check verified. I have found all code which was written by me has inserted into schedulemanagement and all components are integrated together.

**Comment by mzeen** [comment]
now closing this issue.

**Comment by mbaniasad** [comment]
the interface on this part has a few changes
I'm reopening this issue and not creating a
