### ISSUE TITLE
"Line" component implementation

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#18]
- [x]  code for Line 
  - [x] entity
  - [x] dao 
  - [x] management
  - [x] eto
  - [x] restservice
- [x]  Line services 
  - [x] ./lines intreface should be implemented.(check interface document)

**Comment by razadfki** [comment]
@mbaniasad need review, I tested the service interface /lines but getting internal server error.

**Comment by mbaniasad** [comment]
@razadfki nice work. you should continue integrating the buses into this inteface.
check the interface document for the correct output
ask malte for help how to join the tables .
let other's know about the best practices you learned about joining tables and adding list of other objects to another object's json output

**Comment by razadfki** [comment]
@mbaniasad I'll continue working tomorrow and then I'll implement the bus or other interfaces.
