### ISSUE TITLE
lastPosition implementation

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#19]
- [x]  code for lastPosition
  - [x] entity
  - [x] dao 
  - [x] management
  - [x] eto
  - [x] the should be a method for getting the last position of a bus
- [ ] review by reviewer (contact mohammd)

**Comment by rrosemann** [comment]
I'm a bit confused since I thought I should be doing the implementation of the bus component instead.

**Comment by rrosemann** [comment]
Reviewed by me.
