### ISSUE TITLE
Revert the last commit against issue #10

### ISSUE THREAD

**Issue by razadfki** [GSE-Project/SS2016-group1#20]
Undo to the [last commit](https://github.com/GSE-Project/SS2016-group1/commit/4caf6a500018f2d5a83ed9ebc1067fa4b735533f) is required because of the following:
- **rout_id** does not follow the naming conventions i.e., **camelCasing**
-  I have already worked on it and defined it according to the conventions.

**Comment by mbaniasad** [comment]
I have reverted the last commit .
since the route_id in database and routeId in the object are not the same you would need to add some notation .
this inconsistency causes the project to not run at all
please check the samples and commit a runnable version of project as soon as you can.
