### ISSUE TITLE
"Bus" component implementation

### ISSUE THREAD

**Issue by rrosemann** [GSE-Project/SS2016-group1#21]
- [x] code for Bus
  - [x] entity
  - [x] dao
  - [x] management
  - [x] eto
  - [x] restservice
- [x] Bus services
  - [x] ./buses interface implementation
- [ ] review by reviewer
- [ ] verification of interface output with client group

**Comment by rrosemann** [comment]
I created this issue, because it seems to be missing. And also, as far as I can see, it is not the component Malte provided to us. And I did most of the coding today, only need to do some minor fixes.

**Comment by mbaniasad** [comment]
continue on this please.

**Comment by rrosemann** [comment]
Can anyone point me to an example or give some guidance on how to do the interface implementation? I really don't know what to do for that.

**Comment by mbaniasad** [comment]
@ricarda42  check the interface document for correct output.
you should get the output in your browser(ask others if you don't know how).
