### ISSUE TITLE
sariram coming onboard

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#24]
- [x] you should know how to use git and it's issue tracker if you don't learn it.
- [x] you should have a working code on your system (ask others for help) 
- [x] check the line or stop components in the system and learn the structure of the system 
- [x] enter 16 hours of fixed working time in working time card.(#9)
  when you are done with any of the above please check it here.

**Comment by Sriramk88** [comment]
Thanks Moh! I am in the lab right now.

**Comment by mbaniasad** [comment]
@Sriramk88  just did a minor update here

**Comment by Sriramk88** [comment]
hey... I am done with all of the above...

**Comment by mbaniasad** [comment]
close it
