### ISSUE TITLE
R&D for time stamps

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#31]
find the answer to the following questions and let us know what should we follow for the timestamp data type and implementation. and write your answer in the comments 
what are the possible ways of saving timestamps
   using db.
   using java
   etc
which is the best practice.
which is done in the samples.
what are the types that could be use for time stamp.
   which is good for us
   how to convert timestamps from JS clients to server timestamp

what is the difference b/w types: "Date" and "timeStamp" in java

**Comment by Sriramk88** [comment]
we can save timestamps using any of them... sql, java, javascript.
But js could have some compatability issues and of the lot it seems easier to just use Java.

we can use java.sql.timestamp under the date utility, to store the date-time values and perform any functions on it. Its a 'long' datatype.
We can receive the timestamp in the desired format from the clients if required.
sql.date is used to store date and sql.timestamp to store date and time.

**Comment by mbaniasad** [comment]
@Sriramk88 so what is your suggestion?
and please check how should we auto generate the timestamp values (db or java which is better)

**Comment by ChristianAGSE** [comment]
I would propose not to spend to much effort on this. It is only important that you 
- [x] agree on one format, i.e. 2016-05-21T08:31:54MEST(https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations)

-[ ] communicate it to other groups

**Comment by mbaniasad** [comment]
i have already talked to the other teams and updated  the interface document
