### ISSUE TITLE
create component diagram & traceability

### ISSUE THREAD

**Issue by maybeec** [GSE-Project/SS2016-group1#32]
You should start to specify a component diagram as well as the traceability of the system functions to the components.

**Comment by mbaniasad** [comment]
- [x] find a component diagram tool
- [x] sketch the components and discuss it with group
- [x] ask malte for a review on components if changed
- [x] create diagram
- [x] traceability to documents

**Comment by mbaniasad** [comment]
@Sriramk88  first sketch is ready. 
use software idea modeler for creating the creating it.

**Comment by mbaniasad** [comment]
@Sriramk88 any updates on this?

**Comment by mbaniasad** [comment]
@Sriramk88 please link the component diagram in the README.md file as well

**Comment by rrosemann** [comment]
I wil make the link and I am also working on the traceability document. See commit for comments on the diagram (there are some errors)

**Comment by Sriramk88** [comment]
Adding @razadfki to review Component Diagram

**Comment by razadfki** [comment]
@Sriramk88  as it has already been reviewed, here are some pointers
1. Naming of interface should be consistent i.e., camelCasing
2. Real time data interface is fed and read.
3. Use database symbol
4. Depict the layers abstract names
additionally, Christian has opened another issue #62 which is related to this one.

**Comment by Sriramk88** [comment]
@razadfki @ricarda42 updated the component diagram. Included the customstops interface under #62

**Comment by razadfki** [comment]
**Schedules** is still starting with capital s. am I missing something here?
also, database itself is a component or not?

**Comment by Sriramk88** [comment]
Schedules we haven't implemented yet. I've just included it as it might be part of future iterations. I think Malte said that the DB shouldn't be a component.

**Comment by rrosemann** [comment]
Actually schedules has been implemented but is never used in the clients. The relative path is ./schedules. Apart from that, is this now all done? Then please close this issue! It should have been closed yesterday.

**Comment by razadfki** [comment]
just a reminder, ask for **Malte** review as it is also listed in the todo checklist.

**Comment by rrosemann** [comment]
Actually I asked him something about the component diagram. He only had quick look at it, but components haven't been changed anyway. So I guess it should be okay.
