### ISSUE TITLE
Start document a readme

### ISSUE THREAD

**Issue by maybeec** [GSE-Project/SS2016-group1#33]
You should have a readme essentially covering the essential details of your project including how to download and start the latest released server as well as reference the latest documents like:
- [x] component diagram
- [x] traceability matrix from system functions to component diagram
- [x] system test specification
- [ ] traceability matrix from system functions to system tests

**Comment by mbaniasad** [comment]
@Sriramk88 would also help @ricarda42  on this
you don't have to have everything that mentioned above at once. 
do it one by one and start by how to download and run the project
component diagram will be available when #32 has an output
test cases will also be update from issue #15 

first version of traceability matrix. (even not complete should be available ASAP )

**Comment by rrosemann** [comment]
First draft of readme is done. Relevant documents will be linked as soon they exist; installation guide and how to start the server will be added as soon as the first release is done and we know how to do this.

**Comment by rrosemann** [comment]
I'm not sure how to do a traceability matrix for our group since we cannot really relate to interaction cases. Acutally I guess it makes much more sense to have a traceability matrix for all groups together

**Comment by rrosemann** [comment]
Traceability matrix from system functions to test cases still missing, because this is quite easily visible from the test case specification itself. Might still be added in the future.
