### ISSUE TITLE
update server interface specification (May 25)

### ISSUE THREAD

**Issue by maybeec** [GSE-Project/SS2016-group1#34]
Please update and link the interface specification in your readme (#33).
You may want to just generate the wadl, which is already build into JAX-RS technology.

**Comment by ChristianAGSE** [comment]
This is a VERY important issue and MUST be done as soon as possible!

I assigned @mbaniasad . You might shift it to your colleagues.

I set the deadline to Wednesday May 25 due to the importance!

**Comment by mbaniasad** [comment]
took some time to find this
http://localhost:8081/oasp4j-sample-server/services/rest/?_wadl

**Comment by mbaniasad** [comment]
updated the server interface document [here](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces)
