### ISSUE TITLE
Communicate and finalize interface specification

### ISSUE THREAD

**Issue by maybeec** [GSE-Project/SS2016-group1#35]
You should finalize and communicate the interface specification with the other groups to be able to integrate in iteration 2.

GSE-Project/SS2016-group2#37
GSE-Project/SS2016-group3#23

**Comment by maybeec** [comment]
you might want to consider http://geojson.org/ as proposed by group2

**Comment by mbaniasad** [comment]
I would need @razadfki  for help. so just mentioning you here so you get the subscribed to this

**Comment by ChristianAGSE** [comment]
This issue depends on #34, right?

**Comment by mbaniasad** [comment]
@ChristianAGSE yes. basically this and #34 are the duplicate

**Comment by skaldo** [comment]
[Here](https://github.com/GSE-Project/SS2016-group2/wiki/Interface-meeting-outputs#22052016) is the summary of today's meeting (G1 - G2).

**Comment by mbaniasad** [comment]
[here](https://github.com/GSE-Project/SS2016-group1/wiki/interface) there is the result for today's meeting (G1-G3)
