### ISSUE TITLE
Integrate with Clients

### ISSUE THREAD

**Issue by maybeec** [GSE-Project/SS2016-group1#36]
As an outcome of the second iteration, you should present an integrated system running the client APPs with the server backend.

GSE-Project/SS2016-group2#38
GSE-Project/SS2016-group3#24

**Comment by mbaniasad** [comment]
- [ ] discuss with the groups about having a accessible URL
- if deployment needed
  - [ ] find a server for deployment
  - [ ] deploy on the server
  - [ ] deployment script
  - [ ] testing the outcome with clients

**Comment by mbaniasad** [comment]
@bonkilejay 
first step you should be able access an instance of our code in a non localhost system. i. e 
you have to setup a webserver on a system and try to access the our api using another system.
if running our code would be hard try it with a sample code

**Comment by mbaniasad** [comment]
@bonkilejay @Sriramk88  guys any update on this?

**Comment by Sriramk88** [comment]
Uploaded a sample... working on remotely accessing it.

**Comment by skaldo** [comment]
Hi @GSE-Project/group1, do you have deadline for providing the information how to start the server in the readme? Last week @mbaniasad said, that this is going to be done soon.
I'm planning the tasks for next week an I'd be glad if we could run a clone of your server on our machines.

Providing the information to us would be beneficial for you as well, as we could report the possible bugs or interface defects found in your application.

PS: I've already tried `mvn compile`, `mvn install` and `mvn deploy` without success (on https://github.com/GSE-Project/SS2016-group1/commit/d2a9ab92770a43cb974624726664a9dd466436a4).

**Comment by razadfki** [comment]
Hey Dominik,

Please excuse me for the late response as I do not have 
access to development environment and have to do 
everything(jar package) manually since I got your email.

So, attached 
(https://drive.google.com/open?id=0B0XutN0lbC6geC1nanh5RXAwdTQ) 
you'll find a jar package which runs the server on port 
localhost:8080. if you follow the service link i.e., the 
service description then you'll be able to understand the 
URLs you're suppose to call etc.

e.g you should get all the buses against following URL:
http://localhost:8080/services/rest/linemanagement/v1/buses/

Regards,
Hafiz

**Comment by skaldo** [comment]
Hi Hafiz, 
thank you for your response. For me just an estimation would be satisfactory :).
Anyway, thank you for the jar package I'll share it with my team.

So as I understand it, it's not as simple as running several commands to start the server. It would be great if someone from your team could explain the process of building the server to us. But this is definitely not urgent as we have the jar file for now.

Again, thank you for your response! 

BR, 
Dominik

**Comment by themetalone** [comment]
Hey guys. I'm running your server right now. It would be awesome if you would stick to 
[your wiki](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces) since I have a hard time to find the right url to get the data I want

**Comment by mbaniasad** [comment]
Hi. there would be updates on the server today.
the current master branch is not a release yet. to avoid rework keep a mock up of the wiki document as the standard output and do not use the server byitself.

**Comment by Sriramk88** [comment]
Hi... me and @bonkilejay were able to setup the server on a machine today.
We are able to access the data on a client machine.
There are still a couple of components we are having issues with... we'll be working on them tomorrow.

**Comment by mbaniasad** [comment]
@Sriramk88 @bonkilejay .
add a folder named pictures and keep some sample pictures there (e.x bus1picture.png) 
the pictures should be accessible upon request from client

**Comment by razadfki** [comment]
hello @skaldo ,
there is a new entry in wiki as well as in readme file, please have a look at them regarding creating package, deploying and starting server.
Also, you can just download the latest server package(jar) from the release and then can continue your testing.
More, today we tested your app with our server and found few problems which we also tried to fix but unable to do so and hence writing you here.
Please! have look on the mentioned pointers and let us know if you face any problem.

for the record I am tagging the guys that were there while doing all these things: @mbaniasad , @Sriramk88 , @ChristianAGSE  and @ttmher .
Regards,

**Comment by skaldo** [comment]
Thanks @razadfki, I already got it running on my VPS accessible from the internet, so that we can perform the integration tests during the weekend. See: https://github.com/GSE-Project/SS2016-group1/issues/45#issuecomment-223640542 & #54.

**Comment by ChristianAGSE** [comment]
The tests for the second phase are finished.
