### ISSUE TITLE
Bad REST API

### ISSUE THREAD

**Issue by maybeec** [GSE-Project/SS2016-group1#37]
I have seen REST URLs like /getX/ or /setX.
This is essentially not compliant to REST. In REST an operation on the server writing data X would look like /X/ with method POST. Reading X would look like /X/ as well but with GET method.

https://github.com/GSE-Project/SS2016-group1/blob/master/buergerbusserver/core/src/main/java/gse1/buergerbusserver/lastpositionmanagement/service/api/rest/LastPositionmanagementRestService.java

**Comment by razadfki** [comment]
I got it

**Comment by razadfki** [comment]
@maybeec should I refactor the method names as well or just the URL?
