### ISSUE TITLE
Verification against requirements

### ISSUE THREAD

**Issue by rrosemann** [GSE-Project/SS2016-group1#38]
We should check the requirements document and verify our code against the requirements specifications. This should also be documented.

**Comment by themetalone** [comment]
During integration with your server I found that your interface documentation ([Wiki](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces)) does not match your real interfaces. 

You should update your Wiki page (since we adapted your real life interface in our data logic) 

(#36)

**Comment by mbaniasad** [comment]
@themetalone could you please let us know what was wrong specifically?

**Comment by themetalone** [comment]
Within the `stops` each `stops` contains within the schedule an additional timestamp attribute that isn't in the specification.

**Comment by mbaniasad** [comment]
what is not in the wiki would not be the out put of the project. 
the wiki page  is the result of interface meeting with G3 and G2 and can not be updated without confirmation of both groups. what you have mentioned is having more data in the output then it should be, but this data should NOT be used. I have set an issue for this #58

**Comment by themetalone** [comment]
If the wiki page is 'only' the result of the meeting then you should state your provided interfaces. somewhere else. After all we need to integrate with the server and can only do so if we exactly what the server responds at a given rest url. 

Some other changes I found:
- `Bus`, `Line` and `Route` have an additional `timestamp` (just like `Stops`) 
- the `RealTimeBusData` is **NOT** accessible via `host/busses/:id` but via `host/busses/id` (I think the second is the better option although you should tell us somewhere) 
- In `RealTimeBusData` the `delay` property is missing

**Comment by mbaniasad** [comment]
- extra TimeStamp field is removed from the output #58 
- host/busses/:id is an way of writing the address that says the 'id; is a dynamic part. sorry for not clarifying this before. but the current system is using host/busses/id where id can be a number
- delay was added #55

**Comment by ChristianAGSE** [comment]
An ad-hoc review was performed.
