### ISSUE TITLE
realTimeData interface implementation

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#39]
the update of lastPosition  #19 of bus and other data that is related and may get updated like number of seat.. etc
would happen withing in [this](https://github.com/GSE-Project/SS2016-group1/wiki/interface) interface

the interface is 90% finalized. I will update this card when I got the last confirmation from group(3)

I'm mentioning @razadfki here so you can also check the interface and tell if there is something missing

**Comment by mbaniasad** [comment]
interface is finalized

**Comment by rrosemann** [comment]
Why is this still an additional component? Shouldn't it be integrated into the linemanagement component?
This way it does not match our component diagram.

**Comment by mbaniasad** [comment]
@ricarda42 you are correct it should be a part of linemanagement

**Comment by mbaniasad** [comment]
fixed as a commit in issue #19
