### ISSUE TITLE
route interface

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#40]
there are some changes in the interface for route and we are going to use geojson 
you can check the interface document for the changes 
#17

**Comment by mzeen** [comment]
Ok.

**Comment by mbaniasad** [comment]
do not hurry up on this. do the continue on tests first. 1 group's confirmation for geojson is yet waiting

**Comment by mbaniasad** [comment]
interface is finalized.

**Comment by mbaniasad** [comment]
@mzeen I want to help in this. please push your changes and let me know if you have done any changes on this.

**Comment by mzeen** [comment]
I need review on my previous work then I can make the rest.

**Comment by mbaniasad** [comment]
I don't see any previews commit mentioned here. please put a link to your commit and keep in mind to link your commits with the issue

**Comment by mzeen** [comment]
Opsss. Sorry wrong comment on wrong issue
