### ISSUE TITLE
Update interface

### ISSUE THREAD

**Issue by rrosemann** [GSE-Project/SS2016-group1#42]
As documented in the interface document, we need to implement an update method, which upon request sends timestamps of the data in our data base.

**Comment by mbaniasad** [comment]
more info:
it would sent the last timestamps of each of the lists.
so the client knows that he has to refresh the local ofline cache

**Comment by rrosemann** [comment]
I was wondering how this was supposed to work since the stops list is in a different component than the other lists

**Comment by rrosemann** [comment]
@razadfki Did I see it correctly that you have been working on this (in your own branch)? Could you maybe confirm that? Because I was not sure if this was something I should/could do.

**Comment by razadfki** [comment]
@ricarda42 Yes I was working on it but since I'm having problem with the development environment I am unable to continue on it.

**Comment by razadfki** [comment]
I'll continue now with the standard eclipse installation

**Comment by rrosemann** [comment]
The interface does not work on my computer and I am sure I pulled the newest version. Also the "/busses/" interface does not work; and these two are the only ones using the HashMap class I think.

**Comment by rrosemann** [comment]
Ok, it's probably a problem of my computer. If noone else has these problems, we can close this issue again.

**Comment by mbaniasad** [comment]
@bonkilejay please pull the latest version and help @ricarda42 for confirming error
