### ISSUE TITLE
warnings should be fixed

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#47]
there should be no warning in the eclips output

**Comment by ChristianAGSE** [comment]
List (perhaps incomplete) of warnings:
- [x] Comments for public functions

**Comment by ChristianAGSE** [comment]
@bonkilejay: How far are you with this task? Can it be fixed today or are there are any obstacles?

**Comment by bonkilejay** [comment]
@ChristianAGSE I am almost done with this task, just some of the warnings are unresolved .
 Need to confirm some 'warning' issues with @mbaniasad @razadfki . I will most probably fix it today itself

**Comment by razadfki** [comment]
for the Object type warnings we've discussed today, you can use the `@SuppressWarnings("unchecked") or any other appropriate SuppressWarnings` annotation.
remember to add an explanatory comment in that case. [a good reference](http://stackoverflow.com/questions/1129795/what-is-suppresswarnings-unchecked-in-java)

**Comment by bonkilejay** [comment]
Some of the DAO Implementation Files need to be fixed again as they are  fixed with the @SuppressWarnings.

**Comment by rrosemann** [comment]
Is this done now? Please close the issue if yes!

**Comment by bonkilejay** [comment]
yes its done.
