### ISSUE TITLE
Project Setup seems to be platform dependent

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group1#49]
I tried to run your project on my OASP IDE but I encountered some problems while running it

I used `SpringBootApp` as Main type and recieved partially this:

`[D: 2016-06-02 12:50:24,493] [P: WARN ] [C: ] [T: main] [L: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - [M: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'beansJpaConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.Boolean gse1.buergerbusserver.general.configuration.BeansJpaConfiguration.enabled; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'database.migration.auto' in string value "${database.migration.auto}"]  
[D: 2016-06-02 12:50:24,495] [P: INFO ] [C: ] [T: main] [L: org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean] - [M: Closing JPA EntityManagerFactory for persistence unit 'default']  
[D: 2016-06-02 12:50:24,498] [P: INFO ] [C: ] [T: main] [L: org.apache.catalina.core.StandardService] - [M: Stopping service Tomcat]  
[D: 2016-06-02 12:50:24,514] [P: ERROR] [C: ] [T: main] [L: org.springframework.boot.SpringApplication] - [M: Error handling failed]  
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaDataSourceAdvisor': Cannot resolve reference to bean 'methodSecurityMetadataSource' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined
`

The full stack trace can be found [here](http://pastebin.com/KCannNb1)

**Comment by mbaniasad** [comment]
I'm in the lab if you can com we can meet and try to fix it.
but platform should not be an issue
