### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by maybeec** [GSE-Project/SS2016-group1#51]
In the readme you stated, that you have to have a tomcat and deploy a war on it.
That is the complex way to go. As spring comes with an embedded tomcat you can just build the core project and start the packed jar, which will also automatically startup an embedded tomcat.

_Further notice, you might already have seen:
The latest version of your server does not start due to duplicate LineDaoImpl declarations,_

**Comment by mbaniasad** [comment]
@Sriramk88 check this please

**Comment by mbaniasad** [comment]
this is related to #45

**Comment by Sriramk88** [comment]
@maybeec the latest version of the server seems to be working. Could you please elaborate on the error you got.

**Comment by maybeec** [comment]
LineDaoImpl seems to be duplicated. Please check again.
It is not working for me, nor for the other groups as far as I know.

**Comment by Sriramk88** [comment]
Worked with @maybeec . It ran successfully after cleaning the binaries.
For other groups: Please clean the binaries before starting the server.

**Comment by Sriramk88** [comment]
Closing #51
