### ISSUE TITLE
Add a troubleshooting section to the readme.md

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group1#54]
Hi,
I'm using the Debian 7.1, and there is an error `error: unmappable character for encoding ASCII` during the execution of `mvn clean package`. Changing the default encoding using `export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` fixes the issue, but I think you should add this to the readme.md to help others.

I was able to perform all other steps without problems. Thank you for the guide.

BR,
Dominik

**Comment by razadfki** [comment]
Hey,
@skaldo good to hear that you have packaged on your own and also troubleshoot as well :+1: 
 Section of troubleshoot will also be added soon as you've mentioned. actually from our group no one has this OS version and hence didn't face such errors.
Anyway, well done and good luck!
