### ISSUE TITLE
API for bus doesn't return delay

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group1#55]
Hi,
the current API doesn't return any delay. To be consistent, please return this property always. No delay means delay: 0. `/services/rest/linemanagement/v1/busses/1`
Thank you!

BR,
Dominik

**Comment by razadfki** [comment]
hey,
What I know so far, we are just sending the delay as 0 or null at the moment and proper implementation for this variable requires some data to calculate the delay. So, for now we just go with it as it is. ( @mbaniasad just for your notice)
Regards,
Hafiz

**Comment by skaldo** [comment]
Hi,
this is what we get using the yesterday's version:
![screen shot 2016-06-05 at 09 10 20](https://cloud.githubusercontent.com/assets/396663/15804097/62a7c6e2-2afd-11e6-94b8-f9d05cfea71a.png)
Though, it might be that your JSON serialiser does not include the properties with `null` as value at all. If this is the case, try to return `0` instead.

BR,
Dominik

**Comment by razadfki** [comment]
hey,
thank you for the attachment and also I've looked into our code where the delay was mistakenly commented out. it will be fixed soon.
Regards,
Hafiz

**Comment by mbaniasad** [comment]
@razadfki I think this is a fixed issue. if Yes please close the issue
