### ISSUE TITLE
The server does not support CORS

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group1#56]
As the application ios not going to run on the same domain, **please add CORS support**.

In our setup I've configured nginx to do so, but I think that the app should support this OOTB. I made a little research, and it should be as easy as adding the `@CrossOrigin` annotation. But there might be a way how to set this up for the whole service at once, though.

BR,
Dominik

Followup: https://github.com/GSE-Project/SS2016-group2/issues/70

**Comment by maybeec** [comment]
there should be a simply property to set up the cors support. Please have a look at the application.properties.

**Comment by mbaniasad** [comment]
@maybeec  I have tried adding @crossOrigin it it does not [work](http://stackoverflow.com/questions/32140706/spring-cors-controller-annotation-not-working) there is also 
tried adding it using a [filter](http://stackoverflow.com/questions/31724994/spring-data-rest-and-cors) and had no luck.
I need help here

**Comment by razadfki** [comment]
@maybeec you might have forgotten so just a reminder we need your help here.
@mbaniasad follow up continues.

**Comment by mbaniasad** [comment]
@maybeec we need to discuss this in person. in 22nd or 23rd of jun I'm free

**Comment by maybeec** [comment]
23rd would be fine for me. What about 10am?

**Comment by mbaniasad** [comment]
I'm not available on 23rd at 10 -11:30  
any time from 9-10 or 11:30-12:30 or 2-19 is OK  
also I'm available whole day in today (22nd).

**Comment by maybeec** [comment]
ok, please come around at 9am on 23rd.

**Comment by mbaniasad** [comment]
tested with CURL as explained [here](http://stackoverflow.com/questions/12173990/how-can-you-debug-a-cors-request-with-curl)
