### ISSUE TITLE
Setup End-to-End Testing

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#59]
In the testate 3 an end-to-end testing should be presented. This should be prepared.
- [ ] The test preparation requires, that both apps and the server are run.
- [x] At best an externally available server is installed

**Comment by skaldo** [comment]
Regarding this one, feel free to ask me to deploy a jar file on my server.
As I might want to keep old versions of your API on my server, it would be great if the port would be adjustable somehow (maybe command line argument?).

**Comment by mbaniasad** [comment]
server is available thanks to malte  information are available herer:#79

**Comment by mbaniasad** [comment]
@themetalone for running an end to end test I need a running version of your app to be installed on my cellphone. could you please point me to the instructions.

**Comment by skaldo** [comment]
@mbaniasad what is the domain/IP of the server you want to test the app against? I need it in order to build the right version for you.

**Comment by mbaniasad** [comment]
https://digital-villages-server.herokuapp.com/services

**Comment by skaldo** [comment]
Here you go: [android-debug-pre-release.apk.zip](https://github.com/GSE-Project/SS2016-group1/files/334627/android-debug-pre-release.apk.zip).

Please note, all the functionality might not work well, as there's ongoing work to match the interface changes you made yesterday. @themetalone should be done with it later today.

**Comment by themetalone** [comment]
I'll be at the GSE lab at around 14:00 if the public Transport works as it
should

Dominik Skalník notifications@github.com schrieb am Mo., 27. Juni 2016,
12:46:
