### ISSUE TITLE
Ignore build artifacts and eclipse configuration files on commit

### ISSUE THREAD

**Issue by maybeec** [GSE-Project/SS2016-group1#6]
Just as a hint. You should ignore the build folder (target) as well as the eclipse configuration files (.project, .classpath, .settings) on commit to not collide with your colleagues on every push/pull.

**Comment by maybeec** [comment]
Just ignoring them is not enough, you should also remove them from the repository

**Comment by razadfki** [comment]
I have removed the following from the repo (.project, .classpath, .settings) .
Should this issue be close now?

**Comment by maybeec** [comment]
I cannot see the commit referenced to this issue. However, please read the issue description, which also includes the build folder

**Comment by ChristianAGSE** [comment]
Hello,

I will discuss the proper use of issue tracker and/or trello.

Best regards,

Christian

Researcher

Building 32, Room 437 | FB Informatik / AG Software-Engineering (Prof. Rombach)

University of Kaiserslautern | 67653 Kaiserslautern

http://wwwagse.cs.uni-kl.de/ | wolschke@cs.uni-kl.de mailto:wolschke@cs.uni-kl.de  | 0049 631 205 - 3333

Von: Malte Brunnlieb [mailto:notifications@github.com] 
Gesendet: Mittwoch, 11. Mai 2016 08:40
An: GSE-Project/SS2016-group1
Betreff: Re: [GSE-Project/SS2016-group1] Ignore build artifacts and eclipse configuration files on commit (#6)

I cannot see the commit referenced to this issue. However, please read the issue description, which also includes the build folder

**Comment by razadfki** [comment]
@may-bee if this issue is fixed then should we close it?

**Comment by maybeec** [comment]
Yes please. 

-------- Ursprüngliche Nachricht --------
Von: razadfki notifications@github.com
Gesendet: 12. Mai 2016 19:21:15 MESZ
An: GSE-Project/SS2016-group1 SS2016-group1@noreply.github.com
CC: Malte Brunnlieb maltebrunnlieb@web.de, Mention mention@noreply.github.com
Betreff: Re: [GSE-Project/SS2016-group1] Ignore build artifacts and eclipse configuration files on commit (#6)

@may-bee if this issue is fixed then should we close it?

---

**Comment by razadfki** [comment]
okay! this issue (i.e., fixed #6 ) does not require any further commits, so closing it with this comment.
