### ISSUE TITLE
Request custom stop - Adapt Req document

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#60]
- [x] Adapt RE document and add request custom stop
- [x] Review RE document internally + Discuss with other groups
- [x] Review RE with other groups + with Anne
- [x] Discuss open issues with Steffen

**Comment by Sriramk88** [comment]
@mbaniasad spoke to group 3 regarding the custom stops interface... we came up with more questions than answers :)
few things that came up
- the customers can choose any location for their stop
- The Driver can Accept/Decline the request (not sure about this as Christian doesn't want the driver to interact a lot when driving)
- Will all the drivers receive the request (considering there are multiple buses plying at the same time) or do we send it to the driver of the nearest route
- How do we co-relate the time requested by the customer with the bus timings
- If the bus hasn't started on the route, is the customer request accepted by default..?

**Comment by mbaniasad** [comment]
had a talk with @Sriramk88 , @themetalone  and  @ttmher  and waiting for customer confirmation on this
#63 is waiting for the results

**Comment by Sriramk88** [comment]
Worked with @ricarda42 to update the RE document to adapt to the new requirements. Modified existing system functions SF_S10, SF_S11 and added new system function SF_S16.

**Comment by razadfki** [comment]
Hi @Sriramk88 and @ricarda42 ,
I've looked into your system functions and there are few problems. For your convenience I've created a [Sample System Function](https://docs.google.com/document/d/1k5VQUS-fvEKXoekr1bbwPdblli0zRIYh4tqFnPeJ3O8/edit?usp=sharing) .
Please! have a look into it and rewrite and re-review them.

**Comment by Sriramk88** [comment]
Thanks @razadfki . Modified the system functions. Could you review them again.

**Comment by razadfki** [comment]
I commented there in the RE doc file, and also you need to fix the rest of the **System functions** as well, not only the one I specified. I gave an example of one case to follow for all.
@ricarda42 , @Sriramk88

**Comment by Sriramk88** [comment]
@razadfki fixing and reviewing all the System Functions will take time. We should probably create a new issue and work on it separately.

**Comment by rrosemann** [comment]
Hi! I don't think these issues are that important. The other groups have also not followed your sample system function and noone seems to have complained about that. Since this issue should have been closed yesterday, we should just close it for now and continue working. If anyone has spare time, we can still make these improvements. Maybe we can create an issue that is not linked to a milestone and marked as low priority for that.

**Comment by razadfki** [comment]
I didn't have look on other groups' SFs. If you just want to continue(as it looks appropriate up to some extent) then please! just consider that I didn't review at all.

**Comment by rrosemann** [comment]
I admit that it is a lame argument to just say that other groups have also done it the potentially wrong way. The point is that we are running out of time and so we should focus on issues that are more important for the projects progress - like coding the next iteration. We'll definitely keep your comments and suggestions in mind and improve the requirements document whenever we have the time.
