### ISSUE TITLE
Request custom stop - Add system testcase

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#61]
depends on #60 
- [x] extend sys test case (@mzeen)
- [x] review sys test case (@razadfki)

**Comment by razadfki** [comment]
@mzeen there are new tests added in the extended test cases could you please test them so that after that I can review them.
P.S: I've already reviewed some of them.

**Comment by mzeen** [comment]
@razadfki I saw new updates now I will update and let you know for further review.

**Comment by mzeen** [comment]
@razadfki new cases has been tested and document has been updated.

**Comment by razadfki** [comment]
@mzeen thank you I'll review it again and if everything seems ok then I'll close the issue or let you know to close it.

**Comment by mzeen** [comment]
Ok :+1:

**Comment by razadfki** [comment]
@mzeen I have added serial numbers columns, so could you please explain me the scenario no. 15?
one more thing, how did you tested no.16?

**Comment by mzeen** [comment]
@razadfki for Scenario 15: I am testing through this URL "http://localhost:8081/oasp4j-sample-server/services/rest/linemanagement/v1/customStops?lineId={1}" and getting empty list, 
Scenario 16: Ricarda tested it and she added passed in the document. I understood what you mean, If one test is passed so both should pass.

**Comment by mbaniasad** [comment]
try this [http://localhost:8081/oasp4j-sample-server/services/rest/linemanagement/v1/customStops?lineId=1](http://localhost:8081/oasp4j-sample-server/services/rest/linemanagement/v1/customStops?lineId=1)

**Comment by mzeen** [comment]
@mbaniasad Thnaks, Now it is working :+1:

**Comment by razadfki** [comment]
@mzeen you can close the issue now.

**Comment by mzeen** [comment]
#61 all test cases updated and reviewed.
