### ISSUE TITLE
Request custom stop - clarify interface

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#63]
depends on #60
- [x] Perpare interface proposal
- [x] Communicate with Group 2 and 3

**Comment by mbaniasad** [comment]
had a talk with @themetalone and @ttmher  and created the draft interface
waiting for confirmation from customer

**Comment by rrosemann** [comment]
Is this done now? Issue should be closed now...

**Comment by mbaniasad** [comment]
interface is clarified [here](https://github.com/GSE-Project/SS2016-group2/wiki/Interface-meeting-RequestStops) 
- [x] a version should be added to server wiki

**Comment by mbaniasad** [comment]
server wiki update [here](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces)

**Comment by rrosemann** [comment]
The two sources you are refering to here are contradictory. In the interface with group 2 you say that for status requests by citizen we only give three lines with ids and status, whereas in our wiki we are supposed to return the entire entry for the request. How should it be done?

**Comment by mbaniasad** [comment]
@ricarda42  I have already discussed this with @Sriramk88  we would return the complete object. clients can use what they need .
reason is: the addressing is following rest conventions.

**Comment by rrosemann** [comment]
Okay. Did you already tell the clients about it? I think they should know if interfaces change.

**Comment by themetalone** [comment]
No, please tell us :fearful:

**Comment by mbaniasad** [comment]
we did not change any thing. @themetalone  we just giving you  more data then what you need.
you just use what you need from the data
