### ISSUE TITLE
Request custom stop - coding notifications of apps

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#65]
- [x] Prototype should be set up
- [ ] Might be shifted to next iteration
- [ ] Coordinate with group 3

**Comment by mbaniasad** [comment]
@mzeen please update what is done

**Comment by mzeen** [comment]
@mbaniasad sample app is running locally on my pc, it is able to receive notification on android phone sending via browser locally.

**Comment by mzeen** [comment]
now trying to send notification on Android phone through proper internet.

**Comment by mbaniasad** [comment]
moved to iteration 4

**Comment by mbaniasad** [comment]
@GSE-Project/admins .
as I remember in the testate 3 we said that we are not going to have any new feature. dose it imply that the push notification would not be done?  
note: one of our group members is working on this for a while and he said there has been no good out put and we would have struggle in implementing it.

**Comment by mbaniasad** [comment]
@ChristianAGSE I'm waiting for answer on this one.

**Comment by mbaniasad** [comment]
to be implemented in next possible project
