### ISSUE TITLE
Count available Seats

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group1#67]
Discuss with steffen, whether this feature is less important than "Request custom stop".

Then this task might be refined afterwards.

**Comment by Sriramk88** [comment]
Have dropped a mail to Steffen regarding moving available seats feature to the next iteration

**Comment by Sriramk88** [comment]
Steffen agreed that the request custom stop functionality has currently a higher priority than the available seats functionality. Available seats functionality will be implemented in iteration 4.

**Comment by Sriramk88** [comment]
Closing #67

**Comment by ChristianAGSE** [comment]
I reopen the issues, as the functionality should still be implemented in the future. But I will change the milestone to iteration 4.

**Comment by mbaniasad** [comment]
feature implementation and interface is discussed and will be followed in #74 as other groups have requested it

**Comment by razadfki** [comment]
this one is also implemented in #74 , so I'm closing it as well.
