### ISSUE TITLE
Add Stop ID's to Lines Interface

### ISSUE THREAD

**Issue by Sriramk88** [GSE-Project/SS2016-group1#68]
Group 3 requested to add the stop ID's for a particular line to the line interface rather than pick the stops from the stop interface based on the line ID

**Comment by mbaniasad** [comment]
you should mention the people you have talked to.

**Comment by Sriramk88** [comment]
I spoke to Mher

**Comment by mbaniasad** [comment]
I mean mention the git hub  username .so he would get the notified about the discussions here

**Comment by Sriramk88** [comment]
Mher was able to work around this.
Closing #68
