### ISSUE TITLE
Possibility to adjust the port of the server

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group1#69]
Hi there,
it would be great if you could provide a way to adjust the listening port of your server. Some command line argument would be great.

The reason behind this is that I always want to run a legacy version of your application on my server, at least until we double check that everything works fine with the new version.

BR,
Dominik

**Comment by razadfki** [comment]
hello @skaldo ,

for the custom port you need to provide **--server.port** argument i.e.,

 `java -jar buergerbusserver-core-0.1-SNAPSHOT.jar --server.port=portNumber`
see the #71 for document entry

hope that answer the question.
Regards,

**Comment by skaldo** [comment]
Hi @razadfki,
thank you very much for your support, I'll give a try.

BR,
Dominik
