### ISSUE TITLE
managing git branchs

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#77]
- [x] @mzeen  remove rootmanagement branch if not needed
- [x] @Sriramk88 , clarify why server-code branch is needed in the comments here(remove if not needed)
- [x] @bonkilejay stopmanagement and stopmanagement2 branchs should be deleted
- [x] @razadfki  please check your branch and remove it if not needed.

**Comment by bonkilejay** [comment]
Stopmanagement and Stopmanagement_1  deleted.

**Comment by mbaniasad** [comment]
@mzeen, @Sriramk88 please update ASAP

**Comment by Sriramk88** [comment]
removed server code branch

**Comment by mzeen** [comment]
rootmanagement Branch removed

**Comment by mzeen** [comment]
All branches removed now closing issue #77
