### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by maybeec** [GSE-Project/SS2016-group1#79]

**Comment by maybeec** [comment]
open issue here is the alignment of your development branches. What is the actual development branch? Why are there two -> development vs. developmentIt3?
Please adapt the readme accordingly.

**Comment by mbaniasad** [comment]
regarding branches #77 is taking care of it

**Comment by skaldo** [comment]
Hi,
I see that you are now building the server on Travis. It would be great if you could automatically deploy your application. It should not be that hard, as you already have working build definition. I think it should be possible to use the free instance on Heroku.

Here are some links:
- https://docs.travis-ci.com/user/deployment/heroku
- https://devcenter.heroku.com/articles/deploying-spring-boot-apps-to-heroku

**Comment by maybeec** [comment]
@skaldo @pardypaddy 
should be online now at https://digital-villages-server.herokuapp.com/
please test!

@mbaniasad 
heroku will deploy the developmentIt3 branch automatically after successfull travis build.
Please be aware of that, when changing the development branch again. If you need some alignment here, please contact me such that I can reconfigure the branch to deploy from.

**Comment by skaldo** [comment]
It runs, thanks @maybeec, great job!

Unfortunately I cannot test it with our application until the evening. Please someone @GSE-Project/group2, try how it works with our app.

**Comment by mbaniasad** [comment]
@skaldo @maybeec I have never used CI before. this is just awesome. :+1: thanks guys
