### ISSUE TITLE
changes in the interface

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#80]
@Sriramk88 @bonkilejay @razadfki  
your code is not test able since there is no approved  interface document to test it against.  
We need approval in the interface document and a working code that is following the approved interface document. today is the finale day that I have to do the testing. you have to follow other groups to get the approved interface document. and change the document ASAP.

**Comment by Sriramk88** [comment]
@mbaniasad we are waiting for group 2 to respond to our proposed changes. I don't understand what you mean when you say "today is the finale day that I have to do the testing". The testate is on Tuesday 28th.

**Comment by rrosemann** [comment]
Have a look at the Extended test cases document in the developmentIt3 branch. There the URLs are given.

**Comment by rrosemann** [comment]
@mbaniasad @Sriramk88 @bonkilejay
Hi everyone, if you've seen the mail from Steffen, I guess you know we have some serious problems. Their group does not agree with the interface so we have to change it as far as possible. I will try and figure out something during the weekend, please comment if and how you can help in this situation.

**Comment by Sriramk88** [comment]
I think there is a misunderstanding. We are not expecting any kind of user sign in at the Citizen end. We have only made some cosmetic changes. But that said, we should still change the code to reflect the interface as much as possible. I'll try to work on it over the weekend.

**Comment by rrosemann** [comment]
Yes, Steffen wrote again, I think it is not as bad as it sounded in the first place. I'll write another mail tomorrow, maybe we can find a sort of compromise. And also now it is very important to communicate, so anyone doing anything with our code should let the others know, we should push as often as possible and we should stay in close contact to the other groups.

**Comment by rrosemann** [comment]
As you might have seen, I wrote another email to group 2 with a suggestion how to solve this problem quickly. I hope you agree with this. If necessary, I would volunteer to do the rework that needs to be done now. Of course everyone willing to contribute is very welcome!

**Comment by mbaniasad** [comment]
I have sent a mail around.
@Sriramk88 is working on the code and he said soon he would commit some changes. he is done with post method and he is trying to fix the get methods.
@bonkilejay wants to help. but nothing special is in hist hands.

**Comment by Sriramk88** [comment]
I pushed the changes for the post method. Can someone try to run it on their system and verify if its working correctly..?

**Comment by Sriramk88** [comment]
I fixed the get method as well. pushed them. @ricarda42 and @bonkilejay are reviewing and testing the new changes.

**Comment by mbaniasad** [comment]
@Sriramk88 updated the post request. fixed a but also change "name" to "userName"
if you want to change "userName" to "name" it should be done every where not just for the post request.
 and post request also not saveing anything...

**Comment by mbaniasad** [comment]
my bad . saving of request is done and things are ok there

**Comment by mbaniasad** [comment]
@bonkilejay @ricarda42 @Sriramk88  when your job with testing your functionality would be done? please update me when you are done so I do the system tests

**Comment by Sriramk88** [comment]
@mbaniasad could you let me know why we changed it from "name" to "userName"? We wanted it to mirror the interface and in the doc it says "name". We could work on our db changes later. Also, why are you converting coordinates to integer..? they should be double. I am leaving the "userName" as Steffen also seems to be using it and I am moving the changes for the coordinates.

**Comment by mbaniasad** [comment]
@Sriramk88 I have changed them since there was an error poping on when  was trying to use steffen's code. and it was working. I didnot change it completely to int. as you can see still the cast to double was there.  
the reason that I change name to userName was to make it look like what steffen was using. since the output object was returning "userName" not "name" you can not have a post to an address with one entry and a return with another format.

**Comment by rrosemann** [comment]
Code changed and tested so that it exactly matches the interface documentation (and also gives a lot of additional fields, which will be removed when the final interface has been discussed with all groups)
@mbaniasad You can start testing now. If you encounter any errors, please notify us immediately.

**Comment by themetalone** [comment]
I implemented the `userXY` notation

**Comment by mbaniasad** [comment]
@ricarda42 I can see that our code is following the [interface document](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces) but @themetalone is using the userXY notaion.  
it's important that we keep it consistent.
@themetalone I'm sorry but please use the notation as what is in the wiki (we can not afford that your group accepts half of the changes and does not accept the other half.).

**Comment by themetalone** [comment]
We changed our interface since you already implemented it at the time. But I'll revoke the changes.

**Comment by mbaniasad** [comment]
Sorry for the inconvenience

**Comment by themetalone** [comment]
We're back to 

``` JSON
{
  "name":"string",
  "address":"string",
  "assistance":["number"]
}
```

**Comment by mbaniasad** [comment]
thanks 
this is a working  version of the data that should be sent. for you to verify
post to :
https://digital-villages-server.herokuapp.com/services/rest/linemanagement/v1/customStops

```
    {
     "info":{
        "address":"Musterstrasse 5",
        "name":"MaxMustermann",
        "assistance":[1,2,3]
      },
     "lineId":1,
     "deviceID":"random",
     "pickUpTime":1466925880,
     "numberOfPersons":1,
     "location":{
       "type":"Point",
       "coordinates":[111.01,220.01]
     }
    }
```

**Comment by mbaniasad** [comment]
closing this.
anything which has to follow will go to #84
