### ISSUE TITLE
customStops. query parameters are ambiguous 

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#82]
using these combination returns an object  
?requestId=1&deviceId=7  
assumtion is using just one of them should also return an object  
?requestId=1     #no object  
?deviceId=7      #object returned   

@Sriramk88 @ricarda42 @bonkilejay . please clarify for me or confirm that change is needed

**Comment by themetalone** [comment]
We would find it usefull (especially for tetsing purposes) if the server would also respond to a request with only the requestId, i.e.
`.../customStops?requestId=1`

**Comment by Sriramk88** [comment]
@mbaniasad we have implemented only the below three methods as was discussed earlier
?requestId=1&deviceId=7
?deviceId=7
?lineId=1

We could implement the one with just the ?requestId too

**Comment by Sriramk88** [comment]
@mbaniasad @themetalone made changes so that the server now responds to a request with just the requestId

**Comment by mbaniasad** [comment]
tested!
