### ISSUE TITLE
errors when sending empty `assistance` array

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group1#83]
I observed that your server responds with invalid(?) JSON if the request contains an empty `assistance` array. 

``` JSON
{"id":10000020,"modificationCounter":0,"revision":null,"lineId":1,"pickUpTime":1466925880000,"lon":111.000001,"lat":220.000001,"numberOfPersons":1,"deviceId":"random","userName":"MaxMustermann","userAddress":"Musterstrasse 5","userAssistance":"","status":1,"busId":null,"timeStamp":1467016168606,"deviceID":"random"}
{"code":"TechnicalError","message":"An unexpected error has occurred! We apologize any inconvenience. Please try again later.","uuid":"7d794553-c7f6-44dc-998b-1bc5d538149d"}
```

I assume that the problem lies in the second JSON Object. 
- We've got a `TechincalError` although the server responds with `200 OK`
- You should always send only one JSON object. The default rest behavior expects only one object in a http response. A second one breaks the `response.toJson()` method

**Comment by mbaniasad** [comment]
@themetalone  thanks for reporting the bugs :+1:

**Comment by mbaniasad** [comment]
tested
