### ISSUE TITLE
Final Clarification of interface, cleanup of code

### ISSUE THREAD

**Issue by rrosemann** [GSE-Project/SS2016-group1#84]
Talk to the other groups about remaining issues on interface:
- state or status
- deviceID or deviceId
- info { ... } or userName, ...
- interface for delete method? (Or will this only be done internally?)

Remove redundancies in the interface and our code.

**Comment by mbaniasad** [comment]
- [x] I would send a mail to groups regarding small changes in the interface document.
- [x] interface document would be updated
- [ ] @Sriramk88 would implement the changes in the interface document 
- [ ] @ricarda42 and  @bonkilejay, please help @Sriramk88  to remove all the not needed attributes which are provided in the interface
- [ ] @mzeen  review the code. use OASP4j samples as reference
- [ ] I would do the integration , end to end test again. and update the test document

**Comment by mbaniasad** [comment]
@ttmher @themetalone  check [this changes](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces/_compare/aa9b88a82a644431998a0dbc6ec0178035626d8b...f03f2dd29f1883b2f2f55d570110e481695c75c4) on server interface . will update you here when they are done

**Comment by themetalone** [comment]
As far as I see these are only changes in field names. Just tell me when they're done and I can apply them to our code base

**Comment by mbaniasad** [comment]
@Sriramk88 other groups approved [this changes](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces/_compare/aa9b88a82a644431998a0dbc6ec0178035626d8b...f03f2dd29f1883b2f2f55d570110e481695c75c4) on server. please let me know when you would start on it.  
we should also get rid of unwanted fields

**Comment by themetalone** [comment]
Concerning unwanted fields: We would like to use more information from the
`host/customStops?deviceID=xyz`. At the moment we only use the state and
the id. Now we want to use the lineID, busId and pickuptime also. So please
keep them in the interface

mohammad baniasad notifications@github.com schrieb am Di., 5. Juli 2016
um 09:02 Uhr:

**Comment by Sriramk88** [comment]
@mbaniasad I'll start working on it today. Are we still using the developmentIt3 branch or are we working on the new finalDevIt4..?

**Comment by Sriramk88** [comment]
@themetalone we return all the information everytime. Feel free to use anything :)

**Comment by mbaniasad** [comment]
Use what ever branch you want. But keep others informed

**Comment by Sriramk88** [comment]
Implemented the changes to the interface (in finalDevIt4 branch). Working on removing unwanted attributes not mentioned in the interface.

**Comment by rrosemann** [comment]
I noticed that user address, name and assistance are still redundant. Do we want to keep it like this?

**Comment by Sriramk88** [comment]
No... I am working on that.

**Comment by razadfki** [comment]
while commenting the code, I did a review as well. but it's not a complete review (only ,component linemanangent upto package logic, it done).

**Comment by Sriramk88** [comment]
@mbaniasad I am having some difficulty with the converter for the info details. Could we work on this after your exam...?

**Comment by mbaniasad** [comment]
@Sriramk88 I'm in the lab today. please come and we finish this together

**Comment by Sriramk88** [comment]
@mbaniasad till what time will you be in the lab today...? I am outta town and will reach KL around 4pm

**Comment by mzeen** [comment]
Sriram is done with Clarification of interface, cleanup of code. Now closing this issue
