### ISSUE TITLE
Set-up automated testing

### ISSUE THREAD

**Issue by rrosemann** [GSE-Project/SS2016-group1#86]
Testing of code should be automated using travis. See [this](https://travis-ci.org/GSE-Project/SS2016-group1)

**Comment by mbaniasad** [comment]
@bonkilejay @mzeen  please talk to malte and figure out what exactly should be done for automated testing. 
ask for sample  
ask for how to do testing  
ask for tools needed.  
ask for test coverage percentage he wants.  
update here all the questions above.

**Comment by bonkilejay** [comment]
@maybeec  we wanted some help here.
Can we meet ?

**Comment by razadfki** [comment]
it's been a week no update yet?
@bonkilejay , @mzeen

**Comment by mzeen** [comment]
@razadfki , I have created a new branch named as AutomatedTesting and commit some code there. please check it. commit 25e6aaa.

**Comment by mbaniasad** [comment]
I have added a few test that should be run by SOAPUI app which was mentioned [here in the last line](https://github.com/oasp/oasp4j/wiki/guide-soap)

**Comment by mbaniasad** [comment]
@mzeen and @bonkilejay if you can come to lab today I can teach you how to use SOAPUI to setup automated tests.
