### ISSUE TITLE
Update Test documentation

### ISSUE THREAD

**Issue by rrosemann** [GSE-Project/SS2016-group1#87]
Check if all test documents are up-to-date.
Add test cases for newly added methods (see #85)

**Comment by mbaniasad** [comment]
all the cases for status handling should be covered in test   
1. create pending-bus2 accept-bus2
2. create reject-bus1 pending-bus2 accept-bus2
3. create reject-bus1 pending-bus2 reject-bus2 
4. create pending canaled not being shown  
5. crate accept cancel_By_user showing to bus2
6. ...

**Comment by razadfki** [comment]
@mzeen I really need you to work on this and mark it as complete, as soon as possible.

**Comment by rrosemann** [comment]
I would volunteer to create testcases for the status handling, since I think I know quite well what needs to be tested. And also I have spare time right now. I just don't know if it's a problem that I wrote some of the code

**Comment by razadfki** [comment]
yes, I think its a good idea if you start working on it. since you also remember scenarios(we draw on paper and then implemented).

**Comment by mzeen** [comment]
Testes all cases and saved in document. now closing this issue.
