### ISSUE TITLE
Coding of additional methods

### ISSUE THREAD

**Issue by rrosemann** [GSE-Project/SS2016-group1#88]
- Delete method for customStops
- proper status handling, that only sets status to decline, if all busses on the line have declined
- optional: automated delete
- optional: automated decline (shortly before pick-up-time)

(check with customer for optional methods)

**Comment by mbaniasad** [comment]
#93 proper status handling

**Comment by mbaniasad** [comment]
#94 Delete method for customStops

**Comment by rrosemann** [comment]
automated decline not implemented due to time restrictions, automated delete see #94

**Comment by razadfki** [comment]
if that's the case then can we close it?

**Comment by rrosemann** [comment]
Closing due to reasons mentioned above.
