### ISSUE TITLE
Prepare final presentation

### ISSUE THREAD

**Issue by rrosemann** [GSE-Project/SS2016-group1#89]
- Plan content of final presentation
- Prepare sildes
- Discuss how we are going to present

**Comment by mbaniasad** [comment]
I have assigned @mzeen @bonkilejay to this in [here](https://github.com/GSE-Project/SS2016-group3/issues/69) if guys have no time you can also discuss with @ricarda42 and get ready for it.

**Comment by mbaniasad** [comment]
please put a link to storyboard document.  
keep a checklist of TODOs here

**Comment by rrosemann** [comment]
hi @bonkilejay and @mzeen have you done anything on this yet? If not, I might try to adjust the template according to our purposes now. And also we should meet to discuss the content of the presentation. Could you come to the lab Thursday afternoon (from 3:30 p.m. on) or on Friday to discuss these issues?

**Comment by bonkilejay** [comment]
Hi @ricarda42 we (Me and Zeeshan) haven't started working on it yet. 
Regarding the discussion for Final presentation  Friday would be fine for me :) 
@mzeen  Kindly confirm  if Friday would be fine for you .

**Comment by mzeen** [comment]
I will be back at 18:00 from Augsburg. What about weekend? We can meet and
make presentation together.

**Comment by rrosemann** [comment]
I'd say this is not so urgent that we have to spend the weekend on it. Let's start working on it next week, that should be ok. Will you be in the lab on Tuesday?

**Comment by bonkilejay** [comment]
Yes, i 'll be there in the lab on tuesday.

**Comment by mzeen** [comment]
Yes I will be available on next week.

**Comment by rrosemann** [comment]
Hi! I just had a look at all the slides and notes created so far - thanks, guys, for working on it even on the weekend! I wrote some comments at the side. I think the basic contents are there, mostly, but what we need to do now is to put everything together and give it a decent structure. And argue about the points where we disagree ;-) (I have the feeling there are some...) I'll be in the lab tomorrow basically all day, I think we should do that then.

**Comment by rrosemann** [comment]
@GSE-Project/group1 We have just finished the slides, as can be seen [here](https://docs.google.com/presentation/d/160cymNrl2JNBx_7hD-f2EA8oNrf-WUcswKXDrTh6DVo/edit#slide=id.g15592464aa_0_0)
Please have a look and comment.
Also we still need to discuss who is presenting.

**Comment by mzeen** [comment]
We are Finished with the presentation and copy of slides have been sent to Christian also. Now closing this issue.
