### ISSUE TITLE
fix timing to be in the lab

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#9]
every one in @GSE-Project/group1  have to fix 16 hours of work 
it should be in lab 
let the others know about your hours.
Christian said that he would also follow these working hours to check the timing and if there is change in you plan you should tell everyone else about it

**Comment by rrosemann** [comment]
Hours I'll be working in the lab:
Tuesday: 12:30 - 16:30
Wednesday: 11:35 - 17:35
Friday: 10:00 - 16:00

**Comment by mbaniasad** [comment]
Wednesday and Thursdays 11:40 - 19:30

**Comment by mzeen** [comment]
Tuesday and Thursday 11:00 to 18:00

On Wed, May 11, 2016 at 12:16 PM, mohammad baniasad <
notifications@github.com> wrote:

> Wednesday and Thursdays 11:40 - 19:30
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/GSE-Project/SS2016-group1/issues/9#issuecomment-218418803

## 

Muhammad Zeeshan
Master Informatik, TU Kaiserslautern
Mobile:  +49 (0) 152 26368432
http://+49%20%280%2917666199513/
Kaiserslautern, Germany

**Comment by razadfki** [comment]
Monday and Wednesday from 10:00 and 8:00 to onward respectively.

**Comment by bonkilejay** [comment]
Monday , Tuesday ,Wednesday  
11.00 to 5.00

**Comment by ChristianAGSE** [comment]
I collected all data on https://github.com/GSE-Project/SS2016-group1/wiki/LabTimes

The times I can accept so far, but @razadfki: You should tell how long you would stay on these slots.

@Sriramk88: you are still missing in the list.

**Comment by ChristianAGSE** [comment]
Short hint: you might organize a weekly meeting (about 30 minutes) to coordinate the tasks in your group.

**Comment by razadfki** [comment]
@ChristianAGSE for both days 7 hours.

**Comment by mzeen** [comment]
Tuesday and Thursday 11:35 to 18:30.

**Comment by Sriramk88** [comment]
I added my work timings to the wiki

**Comment by rrosemann** [comment]
Christian suggests a weekly meeting, which I think is a very good idea, since communication of what is done and what needs to be done, in my opinion doesn't work that well yet. I suggest Tuesday afternoon, since four of us are in the lab anyway. @mbaniasad, @razadfki please comment, if you could make it Tuesday afternoon at some time. If not, I can maybe make a doodle. Or you can suggest any other date.

**Comment by mbaniasad** [comment]
2:00 - 3:25
or after 5

**Comment by ChristianAGSE** [comment]
as all of you documented your times, I will close the bug.

Changes and also the entering of absense times I would like you to enter at:
https://github.com/GSE-Project/SS2016-group1/wiki/LabTimes
