### ISSUE TITLE
Request State of user canceling

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group1#92]
Hello *,

What state should be send if the user cancels a request. Will `Completed` be sufficent or do you want to use a special state for that event?

[Ref to our Issue](https://github.com/GSE-Project/SS2016-group2/issues/102)

**Comment by mbaniasad** [comment]
@themetalone added 6 as value for "canceled" [here](https://github.com/GSE-Project/SS2016-group1/wiki/server-standard-values) @themetalone 
@ttmher FYI
