### ISSUE TITLE
proper status handling

### ISSUE THREAD

**Issue by mbaniasad** [GSE-Project/SS2016-group1#93]
- [x] I would discus the new interface with other groups
- [x] I would Update the interface document
- [x] @razadfki would implement
- [x] @ricarda42 would review
- [x] @ricarda42 & @mbaniasad discuss the interface/changes with other groups
- [x] @mzeen  would do the end to end test

everyone who is done would mention the next person so he/she knows when to start

**Comment by razadfki** [comment]
hey @mbaniasad ,
could you please discuss this interface on priority, because I see myself to be responsible to implement this and I just want to do it asap due to some time restriction for other things.
thanks!

**Comment by mbaniasad** [comment]
scenario:  
 Citizen/driver wants to know what is the status of a custom stop GIVEN that **there are multiple Buses on the line** where the custom stop is requested.

---

## changes

in customStop object schema the status is which is currently a text would change to a hashMap of bus Id's and values

```
       status:{ "busId1": StatusNumber, "busId2":StatusNumber}
```

where statusNumber is coming from the [wiki](https://github.com/GSE-Project/SS2016-group1/wiki/server-standard-values)
    example: when  a custom stop is accepted by bus with Id "1000" and rejected by bus with Id "2000"

```
    status:{ "1000": 2 "2000":3}
```

---

when the driver is asking for **custom stops** he would just get the custom stops which are important to **his bus**

```
  /customStops?lineId=1&busId=1000&status=1,2
```

this means he would just get the costumStops where either he **accepted** it or it's **pending** for being accepted.

when a custom stop is created for all the available buses in the line the list of status would be increased with status set to **pending**.

custom stops which has **no bus** in their status list (created before there was an active bus) are counted as **pending** custom stops  
    note:the format of Url is subject to change.  
    note: having 1,2  in the url does not necessarily mean you can query for other values as well.

---

**update custom stop status**

driver app will send a list where his **respective statusId** is changed.

   status:{ "1000": 2 "2000":3}

client can not change the status of a custom stop if the custom stop is **accepted** or **completed** by someone else  or marked as **no show up** or **canceled** by another .  
when the **citizen** cancels a custom stop he/she would add his deviceId as key and 6 as value

```
status:{ "1000": 2 "2000":3, "bs1293002":6}
```

-note for server guys: there is no way now to be sure that a bus driver is just changing his own status

initial Status for custom stop  for each bus would be **pending**

**Comment by mbaniasad** [comment]
@ttmher please read the above comment and update me if there is any problem
@razadfki would appreciate a review on above
@themetalone  . this would not have major impact on you. still FYI.

**Comment by mbaniasad** [comment]
@razadfki please review this then I would add it to interface document. other groups are ok with it.

**Comment by razadfki** [comment]
@mbaniasad I'll review it tomorrow and let you know then.

**Comment by mbaniasad** [comment]
scenario:  
 Citizen/driver wants to know what is the status of a custom stop GIVEN that **there are multiple Buses on the line** where the custom stop is requested.

---

## changes

in customStop object schema the status  which is currently a number would stay the same, we would add the busId to busId field if a bus has accepted it

```
       status: StatusNumber,
       busId: Number
```

where statusNumber is coming from the [wiki](https://github.com/GSE-Project/SS2016-group1/wiki/server-standard-values)

---

when the driver is asking for **custom stops** he would just get the custom stops which are important to **his bus**

```
  /customStops?lineId=1&busId=1000
```

this means he would just get the customStops where either 
he **accepted** it  wether it's **canceled** later or not
or it's **pending** for being **accepted** and not **accepted** or **canceled**.

---

**update custom stop status**

driver app will send an update request where status is changed

   status: 1,
   busId: Number

client can not change the status of a custom stop if the custom stop is **accepted** or **completed** by someone else  or marked as **no show up** or **canceled** by another. he would get an error. the content of error yet to be discussed  
when the **citizen** cancels a custom stop he/she would send a request for updating the status to cancel 

```
status: 6
```

**Comment by mbaniasad** [comment]
[the interface doc](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces/_compare/f03f2dd29f1883b2f2f55d570110e481695c75c4...8be90d1f6a4e8bb8200174d9abc8cd61674483dd) document has been updated  
test document should include tests for new cases #87

**Comment by rrosemann** [comment]
Implementation is done now. Since Hafiz and I did this together, I don't know who should review?
Also there is one additional change for the interface: If the customStops are requested via the line, i.e. `./customStops?lineId={lineId}` also the busId needs to be given, i.e. `./customStops?lineId={lineId}&busId={busId}`

**Comment by razadfki** [comment]
has the interface been discussed with other groups? if not, then please let me know so that I could do so.
Also, are the current changes effecting both clients or only one of them(which one?) ?

**Comment by mbaniasad** [comment]
@razadfk @ricarda42 , I'm looking at the interface document and at your code. int your code you are using acceptingBus instead of BusId in the interface.   if ricarda has not discussed the interface to the other groups we can change the interface document. if not the code should be consistent with  the interface

**Comment by razadfki** [comment]
I think, only document change is required plus interface change discussion with other group.
With kind regards,
Hafiz
On Jul 17, 2016 11:46, mohammad baniasad notifications@github.com wrote:@razadfk @ricarda42 , I'm looking at the interface document and at your code. int your code you are using acceptingBus instead of BusId in the interface.   if ricarda has not discussed the interface to the other groups we can change the interface document. if not the code should be consistent with  the interface

**Comment by rrosemann** [comment]
I explained our new code and status handling to one member of group three, so they should know. And group two shouldn't be afffected

**Comment by mbaniasad** [comment]
@ricarda42 I am Updating the docs. [here](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces/_compare/8be90d1f6a4e8bb8200174d9abc8cd61674483dd...493f4ea2be1cdf4c90fb3bd79c9b0b435cb3c9cc)
please take sometime to review it.  
also please let me know if the rejecting buses should also be in the list?

**Comment by mbaniasad** [comment]
@mzeen please take the time and install the apps on your phone or your pc and try an end to end test. also update the respective test documents.

**Comment by rrosemann** [comment]
Thanks for correcting the interface, looks better now ;-) Rejecting Bus will be in the output, although the bus driver app probably won't need it. Actually, I don't know why they should need acceptingBus as well, but I think it's good if it is there, then they know they can use it, if they want to.

**Comment by mzeen** [comment]
end to end test done, now closing this issue.
