### ISSUE TITLE
POST request to 'customStops' fails

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group1#96]
Hi @GSE-Project/group1,
we are getting an error message if we request a new custom stop. Is there a problem on your side, or are we doing something wrong? I remember, that this feature worked before, though.

You can reproduce this issue by making the same request using the postman.

Btw I don't get following:
1) `POST ./customStops. --has return value as described rfc7231` states your wiki, but the _rfc7231_ describes the HTTP protocol. The section 4.3 describes the methods of the HTTP protocol. Maybe you wanted to reference the status codes, but these are described in the section _6._.
Anyway, you wiki does not say anything about the payload of the HTTP POST request for the URL `customStops`.

2) This `"uuid": "aecbd94e-a1fd-4095-abbf-98bcdd3aa18a"` is the part of the response. What is it? I'd understand it as the unique identifier of the device, but `aecbd94e-a1fd-4095-abbf-98bcdd3aa18a` is not equal to the submitted deviceID `somePC`.

**URL:**

```
https://digital-villages-server.herokuapp.com/services/rest/linemanagement/v1/customStops
```

**Request:**

```
{
    "info": {
        "address": "Musterstrasse 5",
        "name": "Max Mustermann",
        "assistance": []
    },
    "lineId": 1,
    "deviceID": "somePC",
    "pickUpTime": 1468492871,
    "numberOfPersons": 1,
    "location": {
        "type": "Point",
        "coordinates": [7.769214212894444, 49.44740110245826]
    }
}
```

**Response:**

```
{
  "code": "TechnicalError",
  "message": "An unexpected error has occurred! We apologize any inconvenience. Please try again later.",
  "uuid": "aecbd94e-a1fd-4095-abbf-98bcdd3aa18a"
}
```

**Comment by rrosemann** [comment]
If you have a look at the interface wiki, you can see that we now use `deviceId` instead of `deviceID` for consistency reasons. Have you tried that already? If this also doesn't work, please comment here again.

**Comment by skaldo** [comment]
Great, thanks @ricarda42!

If I understand it correctly, you have changed the `deviceID` to `deviceId`? If yes, please let us know next time e.g. by opening an issue in our issue tracker.

There's another one, if we want to retrieve the custom stops via
`https://digital-villages-server.herokuapp.com/services/rest/linemanagement/v1/customStops?deviceId=somePC` we get following:

```
[{
    "id": 10000045,
    "modificationCounter": 0,
    "revision": null,
    "lineId": 1,
    "pickUpTime": 1468492871000,
    "location": {
        "type": "Point",
        "coordinates": [7.769214213, 49.447401102]
    },
    "numberOfPersons": 1,
    "deviceId": "somePC",
    "userInfo": "Max Mustermann;Musterstrasse 5;",
    "status": 1,
    "acceptingBus": null,
    "timeStamp": 1468494856226,
    "rejectingBus": null
}] {
    "code": "TechnicalError",
    "message": "An unexpected error has occurred! We apologize any inconvenience. Please try again later.",
    "uuid": "575509b2-c48a-4978-9b5d-31df638dd7d6"
}
```

You do somehow attach an error message to the proper response. Could you please check this too?

**Comment by Sriramk88** [comment]
@skaldo could you try now and let us know if you still see the error. I tried this and it worked correctly.
https://digital-villages-server.herokuapp.com/services/rest/linemanagement/v1/customStops?deviceId=2

**Comment by skaldo** [comment]
Hi @Sriramk88,
the response of this url https://digital-villages-server.herokuapp.com/services/rest/linemanagement/v1/customStops?deviceId=2 is just a empty array:

```
[]
```

For the url mentioned before (https://digital-villages-server.herokuapp.com/services/rest/linemanagement/v1/customStops?deviceId=somePC) I still get the that weird response (which is not compatible with our app):

```
[{
    "id": 10000000,
    "modificationCounter": 0,
    "revision": null,
    "lineId": 1,
    "pickUpTime": 1468492871000,
    "location": {
        "type": "Point",
        "coordinates": [7.769214213, 49.447401102]
    },
    "numberOfPersons": 1,
    "deviceId": "somePC",
    "userInfo": "Max Mustermann;Musterstrasse 5;",
    "status": 1,
    "acceptingBus": null,
    "timeStamp": 1468519928476,
    "rejectingBus": null
}] {
    "code": "TechnicalError",
    "message": "An unexpected error has occurred! We apologize any inconvenience. Please try again later.",
    "uuid": "efaa0057-2226-4cc1-8240-bfcb38939b67"
}
```

Thank you for your support!

**Comment by skaldo** [comment]
@Sriramk88 I have an update:
I've requested a stop with the ID = 2, now the server does not output an empty array anymore, but the same same weird response containing the error message:

```
[{
    "id": 10000001,
    "modificationCounter": 0,
    "revision": null,
    "lineId": 1,
    "pickUpTime": 1468492871000,
    "location": {
        "type": "Point",
        "coordinates": [7.769214213, 49.447401102]
    },
    "numberOfPersons": 1,
    "deviceId": "2",
    "userInfo": "Max Mustermann;Musterstrasse 5;",
    "status": 1,
    "acceptingBus": null,
    "timeStamp": 1468520416861,
    "rejectingBus": null
}] {
    "code": "TechnicalError",
    "message": "An unexpected error has occurred! We apologize any inconvenience. Please try again later.",
    "uuid": "e9b5403d-3bc1-4f6c-a1ce-dab835ac42e2"
}
```

**Comment by skaldo** [comment]
Thanks for fixing this @mbaniasad! The technical error is not being shown anymore.
